window.ORBE_POIS = [
  {
    id: "catedral-capilla",
    name: "Catedral y Capilla Real",
    category: "Historia",
    lat: 37.17630,
    lon: -3.59904,
    emoji: "⛪",
    radiusWalk: 125,
    radiusCar: 260,
    short: "Muy cerca se encuentra el conjunto de la Catedral y la Capilla Real. En la Capilla Real están enterrados Isabel de Castilla y Fernando de Aragón, junto con Juana I, Felipe el Hermoso y el infante Miguel.",
    long: "La Catedral forma parte del gran proyecto de ciudad imperial impulsado bajo Carlos I. A su lado, la Capilla Real fue concebida como panteón de los Reyes Católicos y conserva también los restos de Juana I, Felipe el Hermoso y el infante Miguel. La proximidad de la Madraza y la Alcaicería resume en pocos metros distintas etapas de la historia de Granada.",
    sourceLabel: "Turismo de Granada · Catedral y Capilla Real",
    sourceUrl: "https://turismo.granada.org/es/capilla-real-0"
  },
  {
    id: "madraza",
    name: "Palacio de la Madraza",
    category: "Historia",
    lat: 37.17609,
    lon: -3.59827,
    emoji: "📚",
    radiusWalk: 85,
    radiusCar: 190,
    short: "Aquí se encuentra la Madraza, fundada en 1349 por Yusuf primero y considerada la primera universidad pública de Al-Ándalus.",
    long: "La Madraza Yusufiyya fue fundada en 1349 por el sultán nazarí Yusuf I. Tras la conquista cristiana tuvo distintos usos, entre ellos el de casa consistorial. Actualmente pertenece a la Universidad de Granada y conserva parte de su legado histórico y decorativo.",
    sourceLabel: "Datos contrastados · Universidad y fuentes turísticas",
    sourceUrl: "https://turismo.granada.org/es/que-visitar"
  },
  {
    id: "alcaiceria",
    name: "Alcaicería",
    category: "Historia y comercio",
    lat: 37.17536,
    lon: -3.59919,
    emoji: "🧵",
    radiusWalk: 95,
    radiusCar: 210,
    short: "A pocos metros está la Alcaicería, el antiguo zoco de la seda de la medina islámica de Granada.",
    long: "La Alcaicería era un entramado de calles estrechas dedicado a la fabricación y venta de seda. Se extendía entre el entorno de Plaza Nueva y Bib-Rambla y funcionaba como un recinto protegido. Hoy conserva un ambiente comercial ligado a la artesanía y los recuerdos de Granada.",
    sourceLabel: "Turismo de Granada · Alcaicería",
    sourceUrl: "https://turismo.granada.org/es/monumento/calle-emblematica/alcaiceria"
  },
  {
    id: "bib-rambla",
    name: "Plaza Bib-Rambla",
    category: "Plazas",
    lat: 37.17517,
    lon: -3.59981,
    emoji: "🌺",
    radiusWalk: 100,
    radiusCar: 190,
    short: "Estás cerca de Bib-Rambla, una de las plazas tradicionales del centro y punto de conexión con la Catedral y la Alcaicería.",
    long: "Bib-Rambla ha sido durante siglos un espacio de encuentro y actividad comercial. Su nombre recuerda una de las antiguas puertas de la ciudad y hoy es una plaza peatonal rodeada de terrazas, comercios y puestos de flores.",
    sourceLabel: "Turismo de Granada · Centro histórico",
    sourceUrl: "https://turismo.granada.org/es/barrio-turistico/centro-historico"
  },
  {
    id: "isabel-catolica",
    name: "Plaza Isabel la Católica",
    category: "Historia",
    lat: 37.17546,
    lon: -3.59741,
    emoji: "👑",
    radiusWalk: 105,
    radiusCar: 210,
    short: "Te aproximas a Plaza Isabel la Católica. Su monumento representa a la reina Isabel recibiendo a Cristóbal Colón.",
    long: "El conjunto escultórico de Isabel la Católica y Cristóbal Colón fue realizado por Mariano Benlliure para conmemorar el cuarto centenario del viaje de 1492. La plaza conecta Gran Vía, Reyes Católicos, Pavaneras y el acceso hacia Plaza Nueva.",
    sourceLabel: "Información histórica municipal y patrimonial",
    sourceUrl: "https://turismo.granada.org/es/barrio-turistico/centro-historico"
  },
  {
    id: "realejo-pavaneras",
    name: "Entrada al Realejo por Pavaneras",
    category: "Barrios",
    lat: 37.17480,
    lon: -3.59775,
    emoji: "✡️",
    radiusWalk: 115,
    radiusCar: 220,
    short: "Siguiendo por Pavaneras se entra en el Realejo, el antiguo barrio judío de Granada, conocido como Garnata al-Yahud.",
    long: "El Realejo se encuentra a los pies de la Alhambra y conserva la memoria de la antigua judería granadina. La estatua de Yehudá Ibn Tibon, médico, traductor y erudito, señala la entrada al barrio desde la calle Pavaneras.",
    sourceLabel: "Turismo de Granada · Realejo",
    sourceUrl: "https://turismo.granada.org/es/barrio-turistico/realejo"
  },
  {
    id: "corral-carbon",
    name: "Corral del Carbón",
    category: "Patrimonio nazarí",
    lat: 37.17498,
    lon: -3.59809,
    emoji: "🏛️",
    radiusWalk: 90,
    radiusCar: 180,
    short: "Cerca se encuentra el Corral del Carbón, una alhóndiga nazarí del siglo catorce conservada de forma excepcional.",
    long: "El Corral del Carbón fue una alhóndiga o funduq destinada al alojamiento de comerciantes y al almacenamiento de mercancías. Es uno de los testimonios civiles más singulares de la Granada nazarí y conserva su gran portada y patio interior.",
    sourceLabel: "Patrimonio histórico de Granada",
    sourceUrl: "https://turismo.granada.org/es/que-visitar"
  },
  {
    id: "calle-elvira",
    name: "Calle Elvira y bajo Albaicín",
    category: "Barrios",
    lat: 37.17687,
    lon: -3.59672,
    emoji: "🌙",
    radiusWalk: 120,
    radiusCar: 240,
    short: "A tu alrededor comienza el entorno de Calle Elvira, uno de los accesos históricos al bajo Albaicín.",
    long: "Calle Elvira fue uno de los grandes ejes de la ciudad islámica y conduce hacia la antigua Puerta de Elvira. En su entorno se mezclan patrimonio, comercios, bares y los accesos hacia las Caldererías y las calles del Albaicín bajo.",
    sourceLabel: "Turismo de Granada · Albaicín, Elvira y Paseo de los Tristes",
    sourceUrl: "https://turismo.granada.org/es/rutas/ruta-tapas/albaicin-calle-elvira-paseo-tristes"
  },
  {
    id: "caldereria",
    name: "Calderería Nueva y Vieja",
    category: "Comercio y gastronomía",
    lat: 37.17735,
    lon: -3.59605,
    emoji: "🫖",
    radiusWalk: 110,
    radiusCar: 210,
    short: "Muy cerca están Calderería Nueva y Calderería Vieja, conocidas por sus teterías, dulces, restaurantes y pequeños comercios de ambiente árabe.",
    long: "Las Caldererías enlazan el centro con el Albaicín y forman una de las zonas más reconocibles para disfrutar de teterías, artesanía, especias y gastronomía de inspiración magrebí y oriental. No deben confundirse con la Alcaicería, que era el antiguo mercado de la seda junto a la Catedral.",
    sourceLabel: "Turismo de Granada · Zona Elvira y Calderería",
    sourceUrl: "https://turismo.granada.org/es/rutas/ruta-tapas/albaicin-calle-elvira-paseo-tristes"
  },
  {
    id: "plaza-nueva",
    name: "Plaza Nueva y Santa Ana",
    category: "Plazas",
    lat: 37.17685,
    lon: -3.59587,
    emoji: "⛲",
    radiusWalk: 115,
    radiusCar: 220,
    short: "Llegas a Plaza Nueva, punto de paso entre el centro, el Albaicín, la Carrera del Darro y la subida a la Alhambra por Gomérez.",
    long: "Plaza Nueva es uno de los grandes distribuidores peatonales del centro histórico. Junto a ella se encuentran la iglesia de Santa Ana, la Real Chancillería y los accesos hacia la Carrera del Darro, Calle Elvira y la Cuesta de Gomérez.",
    sourceLabel: "Turismo de Granada · Plaza Nueva",
    sourceUrl: "https://turismo.granada.org/es/monumento/plaza/plaza-nueva"
  },
  {
    id: "carrera-darro",
    name: "Carrera del Darro",
    category: "Paseos históricos",
    lat: 37.17801,
    lon: -3.59402,
    emoji: "🌉",
    radiusWalk: 120,
    radiusCar: 230,
    short: "Te encuentras en el entorno de la Carrera del Darro, una de las calles históricas más antiguas y conocidas de Granada.",
    long: "La Carrera del Darro discurre junto al río, bajo la colina de la Alhambra y al pie del Albaicín. Sus puentes históricos conectan ambas orillas y el recorrido reúne casas, palacios, baños y templos de distintas épocas.",
    sourceLabel: "Turismo de Granada · Carrera del Darro",
    sourceUrl: "https://turismo.granada.org/es/monumento/calle-emblematica/carrera-del-darro"
  },
  {
    id: "paseo-tristes",
    name: "Paseo de los Tristes",
    category: "Paseos históricos",
    lat: 37.17894,
    lon: -3.58937,
    emoji: "🏰",
    radiusWalk: 135,
    radiusCar: 260,
    short: "Has llegado al Paseo de los Tristes, una alameda junto al Darro con vistas privilegiadas de la Alhambra.",
    long: "Su nombre oficial es Paseo del Padre Manjón. El apodo de Paseo de los Tristes procede de los cortejos fúnebres que antiguamente lo atravesaban camino del cementerio situado detrás de la Alhambra. Continúa siendo uno de los espacios más populares para contemplar la fortaleza desde abajo.",
    sourceLabel: "Turismo de Granada · Paseo de los Tristes",
    sourceUrl: "https://turismo.granada.org/es/monumento/calle-emblematica/paseo-tristes"
  },
  {
    id: "parking-san-agustin",
    name: "Entorno del aparcamiento de San Agustín",
    category: "Servicio",
    lat: 37.17755,
    lon: -3.60035,
    emoji: "🅿️",
    radiusWalk: 100,
    radiusCar: 260,
    short: "En el entorno de San Agustín hay un aparcamiento céntrico próximo a la Catedral. Orbe no puede confirmar todavía las plazas disponibles en tiempo real.",
    long: "Este punto se incluye como ejemplo de información práctica. Una versión posterior consultará accesos, restricciones, precios y disponibilidad mediante servicios actualizados, evitando presentar como actual un dato que pueda haber cambiado.",
    sourceLabel: "Punto práctico pendiente de conexión en tiempo real",
    sourceUrl: "https://www.openstreetmap.org/"
  }
];
